[dictionary]
id = "en_us"
name = "English (US)"
description = "English (US) dictionary"

[sources]
text_sources = [
    { repository = "https://github.com/streetsidesoftware/cspell-dicts", path = "dictionaries/en_US/src/additional_words.txt" },
    { repository = "https://github.com/streetsidesoftware/cspell-dicts", path = "dictionaries/en_US/src/acronyms.txt" },
]

hunspell_sources = [
    { repository = "https://github.com/streetsidesoftware/cspell-dicts",aff_path = "dictionaries/en_US/src/hunspell/en_US-large.aff",dic_path = "dictionaries/en_US/src/hunspell/en_US-large.dic"},
]
