[package]
name = "codebook_config"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs.workspace = true
glob.workspace = true
log.workspace = true
regex.workspace = true
serde.workspace = true
toml.workspace = true


[dev-dependencies]
tempfile.workspace = true
