[package]
name = "codebook_config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
glob = "0.3"
log = "0.4.25"
regex = "1.11.1"
dirs = "6.0.0"


[dev-dependencies]
tempfile = "3"
