dictionaries = []
words = [
    "aff",
    "allowlist",
    "codebook",
    "declarator",
    "dic",
    "musl",
    "spellbook",
]
flag_words = [
    "todo",
    "fixme",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
ignore_patterns = ["^[ATCG]+$"]
use_global = true
